import {Dimensions} from 'react-native';
import {APP_HOME_SCREEN_SEARCH_BAR_HEIGHT} from './AppConstants';
import Colors from './Colors';

export const theme = {
  searchMainContainer: {
    backgroundColor: Colors.homeSearchBarBgColor,
    height: APP_HOME_SCREEN_SEARCH_BAR_HEIGHT,
    justifyContent: 'center',
  },
  authLoginEmailTextBox: {
    height: 34,
    width: '80%',
    // marginTop: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 3,
    borderColor: 'lightgrey',
    fontSize: 12,
    fontFamily: 'CeraPRO-Regular',
    color: '#181b1e',
  },
  authLoginPasswordTextBox: {
    height: 34,
    width: '70%',
    padding: 10,
    borderColor: 'lightgrey',
    fontSize: 12,
    fontFamily: 'CeraPRO-Regular',
    color: '#181b1e',
  },
  authLoginTitleLogin: {
    color: '#402E00',
    fontSize: 16,
    fontFamily: 'CeraPRO-Bold',
  },
  authLoginTitleSubPart: {
    color: Colors.secondary,
    fontSize: 17,
    fontFamily: 'CeraPRO-Bold',
  },
  authLoginBtn: {
    alignItems: 'center',
    // padding: 10,
    height: 34,
    backgroundColor: Colors.primary,
    width: '80%',
    borderRadius: 3,
    justifyContent: 'center',
  },
  authLoginBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: 'CeraPRO-Bold',
  },
  authResetPasswordBtn: {
    alignSelf: 'center',
    padding: 10,
    backgroundColor: Colors.primary,
    width: '100%',
    borderRadius: 3,
    marginTop: 12,
  },
  authForgotPasswordEmailTextbox: {
    height: 34,
    width: '100%',
    marginTop: 15,
    borderWidth: 0.5,
    padding: 10,
    borderRadius: 3,
    borderColor: 'lightgrey',
    alignSelf: 'center',
    fontFamily: 'CeraPRO-Regular',
    color: '#181b1e',
  },
  authResetBtnText: {
    textAlign: 'center',
    color: '#ffffff',
    fontSize: 15,
    fontFamily: 'CeraPRO-Bold',
  },

  // top : '14dp',
  // 		text : 'FORGOT PASSWORD',
  // 		font : {
  // 			fontSize : '12sp',
  // 			fontFamily : require('main').fontBold
  // 		},
  // 		color : '#181b

  authForgotPasswordTitleText: {
    color: 'black',
    fontSize: 12,
    fontFamily: 'CeraPRO-Bold',
  },

  authSignupTitleText: {
    color: '#181b',
    fontSize: 16,
    fontFamily: 'CeraPRO-Bold',
    marginTop: 14,
  },
  authSignupTitleTextSubPart: {
    color: Colors.secondary,
    fontSize: 17,
    fontFamily: 'CeraPRO-Bold',
  },
  authSignupEmailMobileOtpTextBox: {
    height: 34,
    fontSize: 12,
    fontFamily: 'CeraPRO-Regular',
    color: '#181b1e',
    flex: 1,
  },
  authSignUpTextBoxContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 3,
    borderColor: 'lightgrey',
    marginTop: '3.75%',
    paddingHorizontal: 5,
    justifyContent: 'space-between',
    width: '100%',
  },

  authSignupPasswordShowHideTouchable: {alignSelf: 'center'},
  authSignupBtn: {
    alignItems: 'center',
    padding: 10,
    backgroundColor: Colors.primary,
    width: '100%',
    borderRadius: 3,
  },
  authSignupBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: 'CeraPRO-Bold',
  },
  authSignupBackToLoginBtn: {
    flexDirection: 'row-reverse',
    marginTop: '10%',
    width: '100%',
    alignSelf: 'center',
  },
  authSignupBackToLoginBtnText: {fontSize: 12, fontFamily: 'CeraPRO-Bold'},
  lblDeliverySpanTime: {
    borderRadius: 12,
    borderColor: '#c3447a',
    backgroundColor: '#f9ecf1',
    borderWidth: 1,
    alignSelf: 'flex-start',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 5,
    paddingRight: 5,
    marginLeft: 5,
    marginTop: 5,
    color: '#4d1930',
    fontSize: 11,
    fontFamily: 'Poppins-Light',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    textAlignVertical: 'center',
  },
  btnAdd: {
    height: 32,
    width: 80,
    //marginRight: 10,
    backgroundColor: '#68a112',
    borderRadius: 3,
    paddingVertical: 4,
  },
  lblAdd: {
    fontSize: 15,
    fontFamily: 'Nunito-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  safeAreaView: {
    flex: 1,
    backgroundColor: 'white',
  },
  defaultBackground: {
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'center',
  },
  splashBackgroundImage: {
    height: Dimensions.get('screen').height,
    width: Dimensions.get('screen').width,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lblPromoText: {
    borderRadius: 12,
    borderColor: '#88b04b',
    backgroundColor: '#b9d194',
    borderWidth: 1,
    alignSelf: 'flex-start',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 5,
    paddingRight: 5,
    marginTop: 5,
    color: '#37471f',
    fontSize: 11,
    fontFamily: 'Poppins-Light',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    textAlignVertical: 'center',
  },
  vwAvailableSizes: {
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 12,
    flexDirection: 'row',
    alignSelf: 'baseline',
    alignItems: 'center',
    height: 32,
    borderWidth: 1,
    borderColor: '#d2d2d2',
  },
  lblSelectedSize: {
    color: '#676972',
    fontSize: 14,
    fontFamily: 'CeraPRO-Regular',
    textAlignVertical: 'center',
  },
};
