export default {
  PRODUCTS: {
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_SEARCH_SUCCESS : 'PRODUCT_SEARCH_SUCCESS',
    IS_LIST_VIEW : 'IS_LIST_VIEW',
    IS_GRID_VIEW : 'IS_LIST_VIEW'
  }
};
