export default {
  PRODUCTS: {
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    MORE_PRODUCT_LIST_SUCCESS: 'MORE_PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_ERROR: 'PRODUCT_LIST_ERROR',
    MORE_PRODUCT_LIST_ERROR: 'MORE_PRODUCT_LIST_ERROR',
    FILER_SUCCESS: 'FILER_SUCCESS',
    FILER_ERROR: 'FILER_ERROR',
    FILTER_APPLY_SUCCESS: 'FILTER_APPLY_SUCCESS',
    FILTER_APPLY_FAILURE: 'FILTER_APPLY_FAILURE',
    SAVE_FILTER_STATE_SUCCESS: 'SAVE_FILTER_STATE_SUCCESS',
    SAVE_FILTER_STATE_FAILURE: 'SAVE_FILTER_STATE_FAILURE',
    PRODUCT_LIST_LEFTMENU_SUCCESS: 'PRODUCT_LIST_LEFTMENU_SUCCESS',
    PRODUCT_HOMESCREEN_WIDGET_SUCCESS: 'PRODUCT_HOMESCREEN_WIDGET_SUCCESS',
    PRODUCT_HORIZONTAL_SUBCATEGORIES_SUCCESS : 'PRODUCT_HORIZONTAL_SUBCATEGORIES_SUCCESS',
    PRODUCT_HORIZONTAL_SUBCATEGORIES_FAILURE : 'PRODUCT_HORIZONTAL_SUBCATEGORIES_FAILURE',
    PDP_WIDGET_FBT_DATA_SUCCESS : 'PDP_WIDGET_FBT_DATA_SUCCESS',
    PDP_WIDGET_YMAL_DATA_SUCCESS : 'PDP_WIDGET_YMAL_DATA_SUCCESS',
    PDP_WIDGET_PAB_DATA_SUCCESS : 'PDP_WIDGET_PAB_DATA_SUCCESS',
    PL_RECOMMENDED_PRODUCTS_SUCCESS : 'PL_RECOMMENDED_PRODUCTS_SUCCESS'
  }
};
