export default {
  PINCODE: 'Pincode',
  MOBILE: 'mobile_no',
  WAREHOUSEID: 'WarehouseID',
  CITYID: 'CityID',
  CITYNAME: 'CityName',
  ISPANINDIA: 'IsPanIndia',
  DELIVERYDAYS: 'DeliveryDays',
  ISCST: 'IsCST',
  ISRAPID: 'IsRapid',
  PRIVATEKEY: 'privatekey',
  FLAGID: 'flagID',
  USERID: 'userID',
  ISGUESTLOGIN: 'isGuestLogin',
  USERNAME: 'UserName',
  USEREMAIL: 'UserEmail',
  ADDRESS: 'address',
  SELECTED_DATE: 'selected_date',
  SELECTED_TIME_SLOT_ID: 'selected_time_slot_id',
  ZONE_SLOT_ID: 'zone_slot_id',
};
